<a href="https://colab.research.google.com/github/ZehraArshad/DS-Projects/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

*Introduction
*Getting info from tensors
*Manipulating tensors
*Tensors & Numpy
*Using @tf.function(a way to speed up your python functions)
*Using GPUs with Tensorflow(or TPUs)


SyntaxError: ignored

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
#Creating Tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#Check the number of dimensions of a tensor (ndim stands for no of dimensions)
scalar.ndim

0

In [4]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#Check the dimensions of our vector
vector.ndim

1

In [6]:
#Create a matrix (Matrix has more than one dimension)
matrix =tf.constant([[10, 7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[3.,4.],
                              [2.,4.],
                              [3.,6.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 4.],
       [2., 4.],
       [3., 6.]], dtype=float16)>

In [9]:
#float16 takes less space than int32
 
 #What is the number of dimension of another_matrix?
another_matrix.ndim

2

In [10]:
#How to create more dimensions?
#By creating a tensors
tensor = tf.constant([
                        [[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

Scalar: a signle number

Vector: a number with direction (e.g. wind speed and direction)

Matrix: a 2-dimensional array of numbers

Tensor: an n-dimensional array of numbers (0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


Creating tesnors with tf.Variable

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])

In [13]:
#Changing one of the elements
changeable_tensor[0] = 7 -> Tensor doesn't support


SyntaxError: ignored

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
unchanegable_tensor[0].assign(7)
unchangeable_tensor 

NameError: ignored

In [16]:
#Creating random tensors
# Random tensors are tensors of some arbitary size which contain random numbers
random_1= tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 =tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#Are they equal
random_2, random_1, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffling is always good to avoid overfitting


In [17]:

# Shuffle a tensor(inherent order doesn't affect learning)
not_shuffled =tf.constant([[2,3],
                           [3,4],
                           [5,6]
])
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [2, 3],
       [3, 4]], dtype=int32)>

In [ ]:
#1:41 -> assignment

In [18]:
tf.random.set_seed(42) # global random
tf.random.shuffle(not_shuffled, seed=42) #random level

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4],
       [5, 6]], dtype=int32)>

When random and global are same then you will get same result -> Rule 4 in documentation

In [19]:
tf.ones([10,6])

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
#Create a tensor with all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

**Difference between Tensors and Numpy**
*   tensors can be run on a GPU

In [21]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector)      # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4)) #these numbrs should multiply to 24
A,B # 2*3*4 // # 3*8


(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

Getting more info from tensors 


*   Shape
*   Rank
*   Axis/dim
*   Size




In [26]:
  # Create a rank 4 tensor (4 dimensions)
  rank_4_tensor = tf.zeros(shape=[2,3,4,5])
  rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor))
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of elements: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements: 120


In [29]:
 #first two elements of each dimensions
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
#Get first element from each dimension except the last one
rank_4_tensor[:1,:1,:1] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[:1,:1,:1,:1] # -> flatening out the dimensions

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [32]:
# rank 2 tensors
rank_2_tensor=tf.zeros(shape=[2,3])
rank_2_tensor
rank_2_tensor.ndim

2

In [33]:
#another way for rank_2
rank_2_tensor=tf.constant([[10, 7],[3,4]])
rank_2_tensor.ndim

2

In [34]:
#getting last element of rank_2_tensors
rank_2_tensor[:,-1] #-> : means all like matlab

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [35]:
#adding a dim for NEURAL NETWORK
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor



<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
rank_3_tensor= rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
#or
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means add extra dim on the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [38]:
#Manipulating tensors
# +, -, *
tensor = tf.constant([[10, 7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
# Matrix multiplication
A = [[10, 4, 5],
     [4, 5, 6],
     [8, 4, 10]]
B = [[12, 23],[12, 6],[5, 6]]
tf.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[193, 284],
       [138, 158],
       [194, 268]], dtype=int32)>

In [40]:
B

[[12, 23], [12, 6], [5, 6]]

In [41]:
 A =[[1, 2, 5],[7, 2, 1],[3, 3, 3]]
 B=[[3, 5],[6, 7],[1, 8]]
 tf.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [42]:
# multiply matrix of same size 3 x |2 != 3| x 2 -> change shape of these meatrix
# tf.reshape (Y, shape=(2,3))



In [43]:
#Changing the datatypes -> reducing size
B =tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [44]:
B= tf.cast(B, dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [45]:
A = tf.constant([10, 4])
A , A.dtype



(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>,
 tf.int32)

In [46]:
A = tf.cast(A , dtype= tf.float32)
A, A.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  4.], dtype=float32)>,
 tf.float32)

In [47]:
 #Aggregating sensors
 # condensing them from multiple values down to smaller amount of values
T = tf.constant(np.random.randint(0,100, size=50))
T


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([31, 32, 39, 69,  4, 24, 36, 67, 96, 39, 10, 53, 74,  7, 97, 77, 26,
       64, 35, 79, 23, 29, 87, 93,  5, 63, 39,  5, 60, 45, 17, 50, 27,  4,
       61, 48, 97,  1, 38, 80, 15, 93, 16, 32, 29, 85, 82, 84,  1, 84])>

In [48]:
tf.reduce_min(T)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [49]:
tf.reduce_max(T)


<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [50]:
tf.reduce_mean(T)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [51]:
tf.reduce_sum(T)

<tf.Tensor: shape=(), dtype=int64, numpy=2352>

In [52]:
# standard deviation and variance
import tensorflow_probability as tfp
tfp.stats.variance(T)

<tf.Tensor: shape=(), dtype=int64, numpy=907>

In [53]:
import math as m

In [54]:
m.sqrt(788)

28.071337695236398

In [55]:
T

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([31, 32, 39, 69,  4, 24, 36, 67, 96, 39, 10, 53, 74,  7, 97, 77, 26,
       64, 35, 79, 23, 29, 87, 93,  5, 63, 39,  5, 60, 45, 17, 50, 27,  4,
       61, 48, 97,  1, 38, 80, 15, 93, 16, 32, 29, 85, 82, 84,  1, 84])>

In [56]:
#find positional max and min -> at which index does the max lies or min lies
tf.argmax(T)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [57]:
tf.argmin(T)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [58]:
# to find that value
T[tf.argmax(T)]

<tf.Tensor: shape=(), dtype=int64, numpy=97>

**One hot encoding**

In [61]:
t_list = [0, 1, 2, 3]
t_list
tf.one_hot(t_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [63]:
#Specifying custome values for OHE
tf.one_hot(t_list, depth=4 , on_value="Hello", off_value="Bye")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Bye', b'Hello', b'Bye', b'Bye'],
       [b'Bye', b'Bye', b'Hello', b'Bye'],
       [b'Bye', b'Bye', b'Bye', b'Hello'],
       [b'Bye', b'Bye', b'Bye', b'Bye']], dtype=object)>

**Tensors and Numpy**

In [64]:
#Create a tensor from a numpy array
J =tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [65]:
#Convert our tensor to a numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [70]:
#Convert tensor J to a Numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [72]:
J= tf.constant([3.])
J.numpy()

array([3.], dtype=float32)

In [73]:
#the default datatypes of each are a bit different
numpy_J=tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

**Regressions -> always asking a number**
*   How much
*   how many

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>